name: Post ISO20022 to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ISO20022 file
        run: wget -O iso20022.xml "https://danskeci.com/-/media/pdf/danskeci-com/iso-20022-xml/camt052_accountentries_example_fi.xml"

      - name: Read ISO20022 content
        run: |
          echo '```xml' > formatted_iso20022.xml
          cat iso20022.xml >> formatted_iso20022.xml
          echo '```' >> formatted_iso20022.xml

      - name: Post comment to PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat formatted_iso20022.xml)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}