name: Post ISO20022 to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ISO20022 file
        run: wget -O iso20022.xml "https://danskeci.com/-/media/pdf/danskeci-com/iso-20022-xml/camt052_accountentries_example_fi.xml"

      - name: Read ISO20022 content
        run: |
          echo '```xml' > formatted_iso20022.xml
          cat iso20022.xml >> formatted_iso20022.xml
          echo '```' >> formatted_iso20022.xml

      - name: Post comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT=$(jq -Rs . < formatted_iso20022.xml)
          PR_URL="${{ github.event.pull_request.comments_url }}"
          curl -s -X POST "$PR_URL" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": $COMMENT}"
